### ISSUE TITLE
A Calendar on the homepage, right of the second carousel. 

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#11]
See [IIT Bombay's page for reference] (http://ecell.in).

**Comment by kaushalvivek** [comment]
IIT-B's calendar is ugly. Very. 
We have to make it better.

**Comment by Pk13055** [comment]
#21
I've set up the jQuery calender plugin, but for some reason it isn't rendering. 
@nemaniarjun Take a look?

**Comment by nemani** [comment]
Calender is not rendering cause you added the wrong CDN for moment.
The correct one is : < https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js >

**Comment by nemani** [comment]
Look into resize-ing issues

**Comment by nemani** [comment]
Also why are you using 2 css? 
Full calender.css and fullcalender.print.css?
Optimize it however

**Comment by Pk13055** [comment]
#22
