### ISSUE TITLE
Dropdown Menu should pull back up instead of slow fade

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#13]
The slow fade is causing usability problems. I fixed the dropdown menu size and location, work still needed on the animation.

**Comment by nemani** [comment]
Which page is this regarding?

**Comment by kaushalvivek** [comment]
Home. To be fixed in the index.

**Comment by nemani** [comment]
If its just usablity issues, I suggest just speeding up the fade.
The default was 225 according to materalize website, we for some reason changed it to 2000 :P

**Comment by nemani** [comment]
Or we can change it to slideUp?

**Comment by kaushalvivek** [comment]
Yes, I changed it to 2000, because when it's 225, you can't really choose any options, for some reason, the focus does not hold when you move your cursor to options. So essentially, no option can be chosen. Making it pull up should work, or even a fix for the focus would work.
