### ISSUE TITLE
Home Page Carousel, Static Images not rendered

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#16]

**Comment by nemani** [comment]
Which static pictures is this regarding?
Photos of food and people's quotes, (Both carousals) render for me.

**Comment by kaushalvivek** [comment]
Both the carousals are sourced from online images, try rendering local images, that did not seem to work for me.

**Comment by kaushalvivek** [comment]
@nemaniarjun This is an important one, is it working for you?

**Comment by kaushalvivek** [comment]
@mridulnagpal Have a look, when you're free.

**Comment by nemani** [comment]
umm, they work for me

**Comment by Pk13055** [comment]
Working here too.
@kaushalvivek Are you using  ` src="{% static '<image location> ' %} ` ? _(location relative to the STATIC folder)_

**Comment by kaushalvivek** [comment]
fixed
