### ISSUE TITLE
Google Map for IIIT not rendered in Django

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#18]
See the code for the map, it works with normal HTML, but is not being rendered on the server.
PS: An API key has already been generated, use the same.

**Comment by Pk13055** [comment]
#24

**Comment by Pk13055** [comment]
![screenshot from 2017-05-28 23-42-01](https://cloud.githubusercontent.com/assets/13479308/26531085/30ab0abc-43d1-11e7-9578-0639c3e3f1ca.png)

**Comment by Pk13055** [comment]
@kaushalvivek I think this looks good enough; tell me if any other changes are required.

**Comment by kaushalvivek** [comment]
Looks good.
