### ISSUE TITLE
Text Animation on Scroll

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#28]
Text animation on index page should be triggered by scrolling, when the element is in focus.

**Comment by nemani** [comment]
Its called a scrollspy I guess

**Comment by kaushalvivek** [comment]
[A Scrollspy](https://www.w3schools.com/bootstrap/bootstrap_scrollspy.asp) seems a little different. What I had in mind was a simple animation fadeIn which is triggered when we scroll down to the portion with the animation. Eg, right now, the "WHO ARE WE?" text has an animation, but it's triggered when the page loads, and the user does not see it, I want the user to see it, for that the animation has to happen when the user scrolls down to that part.

**Comment by Pk13055** [comment]
What we want is something like [this](http://materializecss.com/scrollfire.html). I'll try incorporating it.

**Comment by Pk13055** [comment]
For now, let this slide. Once a dynamic backend is in place, then we can look into adding animations and effects. Closing this, for now.
