### ISSUE TITLE
Mixed CSS?

### ISSUE THREAD

**Issue by Pk13055** [gokulbnr/E-Cell-Website#32]
`Base.html` uses bootstrap column grid, while using the flexbox structure (and other classes) provided by materialize. Is this intentional or ..?

**Comment by Pk13055** [comment]
#29

**Comment by kaushalvivek** [comment]
Intentional, had to resort to whatever worked quickest for a lack of time.
We can standardise the code after we have a draft of the final end product, the site goes live in a day.
Make suitable changes if you have to, to fix other issues.

**Comment by Pk13055** [comment]
#33
