### ISSUE TITLE
Team Cards to be removed and replaced by Materialize hoverable panels

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#39]

**Comment by Pk13055** [comment]
CSS was pretty screwed up. Redid them in materialize, tell me how this color looks 
![screenshot from 2017-07-13 09-50-21](https://user-images.githubusercontent.com/13479308/28147094-c1277582-67b0-11e7-9848-cf36486089c0.png)
@kaushalvivek

**Comment by Pk13055** [comment]
(PS - would appreciate adding our details to the core team too ;P) @nemaniarjun

**Comment by kaushalvivek** [comment]
Looks good to me, but I am not the one calling the shots. :/
Let's see what the head has to say.

**Comment by nemani** [comment]
@pk13055 check if you can duplicate the cards. And see if you run into any issues with multiple cards

**Comment by Pk13055** [comment]
I don't remember the original color scheme. I'll be able to duplicate them
if you give me a photo of the original

**Comment by nemani** [comment]
No what I meant is try the case where we have a lot of cards. Make sure the padding and all is fine

**Comment by nemani** [comment]
Like when we have multiple rows and columns

**Comment by Pk13055** [comment]
Padding is fine, tested statically already, check if the color scheme is okay? @kaushalvivek

**Comment by kaushalvivek** [comment]
@Pk13055 Looks good to me, I'll run it by her once.

**Comment by Pk13055** [comment]
Okay, merging now; raise a new issue for any more color changes etc. Group together the issues under one issue so that tracking will be easier.

**Comment by Pk13055** [comment]
#42

**Comment by kaushalvivek** [comment]
![screen shot 2017-07-14 at 5 08 40 pm](https://user-images.githubusercontent.com/19169641/28210900-774082bc-68b7-11e7-9ddb-3894220b58f6.png)
It goes to shit on mid-sized screens :3, wtf

Restoring the original cards with a decorative makeover.

**Comment by nemani** [comment]
The original css was copied from the coala web site, its complicated but
works like a charm. I tried it with a 100 cards too. Looks perfect.

**Comment by kaushalvivek** [comment]
Yeah, the original cards worked like a charm, I'll restore that for now.
With a few colour changes.

**Comment by Pk13055** [comment]
No device has the screen res of what the example is, I've tried it on an actual mid size device (iPad) and it worked fine. Switch back to the original but make a CSS file? 

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kaushalvivek** [comment]
Yeah, done, this is fixed.
Will post other issues, new ideas have been suggested.
