### ISSUE TITLE
Flow-text Font size to be reduced

### ISSUE THREAD

**Issue by kaushalvivek** [gokulbnr/E-Cell-Website#40]
This has to be done keeping in mind that the text should not be too small for mobile devices

**Comment by Pk13055** [comment]
Tested on mobile, font-size seems perfect for the given display.

**Comment by Pk13055** [comment]
Also, the whole point of flow-text is to have dynamic text size that looks _perfect_ on every screen size. - Closing this for now

**Comment by kaushalvivek** [comment]
I presented the site, and we have to reduce the size, It does look good on small screens, but it's too big on PC screens, we'll have to address that, if that can be done on the flow-text class.
(Edit the materialize css?)
If not, we'll go ahead and use standard text.

**Comment by Pk13055** [comment]
@kaushalvivek We'll have to use standard CSS only. The whole point of `flow-text` is to have something dynamic; notice how it changes with *every* minuscule change in display size. What did she say though? Overall?

**Comment by kaushalvivek** [comment]
She liked it, requested some changes though, those are the issues I raised.
I'll have a look at the text thing today, have been a little busy. :\

**Comment by Pk13055** [comment]
Raise a common issue, with all the minor changes; makes no sense to have multiple issues for just a few lines of code, even if they aren't related.
